print("""Hey guys!, Excited to generate your Band Name, 
Here we go..!""")
city=input("Which city you live in or any city you like?\n")
pet=input("what is your pet name ,if not then any name you like?\n")

print("Name Generated by Band Generator is",(city)+(" ")+(pet))
